CoolWebsite/Controllers/AuthController.cs
using System.Threading.Tasks;
using CoolWebsite.Application.Common.Interfaces;
using CoolWebsite.Domain.Entities.Identity;
using CoolWebsite.Infrastructure.Identity;
using CoolWebsite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CoolWebsite.Controllers
{
    public class AuthController : Controller
    {
        private readonly IIdentityService _identityService;

        public AuthController(IIdentityService identityService)
        {
            _identityService = identityService;
        }
    
    
        public RedirectToActionResult Logout()
        {
             _identityService.Logout();
            return RedirectToAction("Index", "Home", new {area=""});
        }
    }
}

CoolWebsite/Views/Shared/Sidebar.cshtml
@using CoolWebsite.Services
@*<nav class="navbar navbar-expand navbar-dark bg-dark fixed-left ">
  <a class="navbar-brand" href="#">Cool Website</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse top-div " id="navbarColor02">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-area="" asp-controller="Home">Home<span class="sr-only">(current)</span></a>
      </li>
          
      @{
        if (User.IsInRole("Admin"))
        {
          <li class="nav-item">
            <a class="nav-link nav-dropdown-activator" >User mangenment</a>
            <ul hidden="" class="dropdown-nav">
              <li class="nav-item">
                <a class="nav-link" asp-area="UserManagement" asp-action="Index" asp-controller="Roles">Roles</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="UserManagement" asp-action="Index" asp-controller="Users">Users</a>
              </li>
            </ul>
          </li>
        }
      }
            
      <li class="nav-item">
        <a class="nav-link" asp-area="Financial" asp-action="Index" asp-controller="Home">Financial</a>
      </li>
    </ul>
  </div>
  <div class="bottom-div">
    <ul class="navbar-nav mr-auto bottom-div-list">
      <li class="bottom-div-list">
        <span>@User.Identity.Name</span>
        <a class="nav-link text-danger" asp-area="" asp-controller="Auth" asp-action="Logout">Log out</a>
      </li>
                
    </ul>
  </div>
</nav>
*@

<a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <a asp-action="HomePage" asp-controller="Home" asp-area="">CoolWebsite</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        <div class="user-pic">
          <img class="img-responsive img-rounded" src="~/img/Homepage/d5802db4-4b7b-48a1-a67a-e0b15f34bafb_200x200.png"
            alt="User picture">
        </div>
        <div class="user-info">
          <span class="user-name">
            
            @User.GetFirstName()
            <strong>
              @User.GetLastName()
            </strong>
          </span>
          @if (User.IsInRole("Admin"))
          {
            <span class="user-role">Administrator</span>
            
          }
          else
          {
            <span class="user-role">Standard User</span>
          }
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
      </div>
      <!-- sidebar-header  -->
    @*
      <div class="sidebar-search">
        <div>
          <div class="input-group">
            <input type="text" class="form-control search-menu" placeholder="Search...">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      *@
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>Financial</span>
          </li>
          <li>
            <a asp-action="Index" asp-controller="Home" asp-area="Financial">
              <i class="fa fa-folder"></i>
              <span>Projects</span>
              @*<span class="badge badge-pill badge-warning">New</span>*@
            </a>
          </li>
          <li>
            <a asp-action="Index" asp-controller="Transaction" asp-area="Financial">
              <i class="fa fa-money-check-alt"></i>
              <span>Transactions</span>
              @*<span class="badge badge-pill badge-warning">New</span>*@
            </a>
            
          </li>
          <li>
            <a asp-action="Index" asp-controller="Archive" asp-area="Financial">
              <i class="fa fa-archive"></i>
              <span>Archive</span>
              @*<span class="badge badge-pill badge-warning">New</span>*@
            </a>
            
          </li>
          @*
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-shopping-cart"></i>
              <span>E-commerce</span>
              <span class="badge badge-pill badge-danger">3</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Products

                  </a>
                </li>
                <li>
                  <a href="#">Orders</a>
                </li>
                <li>
                  <a href="#">Credit cart</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="far fa-gem"></i>
              <span>Components</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">General</a>
                </li>
                <li>
                  <a href="#">Panels</a>
                </li>
                <li>
                  <a href="#">Tables</a>
                </li>
                <li>
                  <a href="#">Icons</a>
                </li>
                <li>
                  <a href="#">Forms</a>
                </li>
              </ul>
            </div>
          </li>
        <li class="sidebar-dropdown">
          <a href="#">
            <i class="fa fa-chart-line"></i>
            <span>Charts</span>
          </a>
          <div class="sidebar-submenu">
            <ul>
              <li>
                <a href="#">Pie chart</a>
              </li>
              <li>
                <a href="#">Line chart</a>
              </li>
              <li>
                <a href="#">Bar chart</a>
              </li>
              <li>
                <a href="#">Histogram</a>
              </li>
            </ul>
          </div>
        </li>
                  *@
        @if (User.IsInRole("Admin"))
        {
          <li class="header-menu">
            <span>User Management</span>
          </li>
          <li>
            <a asp-action="Index" asp-controller="Users" asp-area="UserManagement">
              <i class="fa fa-book"></i>
              <span>User</span>
              <span class="badge badge-pill badge-primary">Beta</span>
            </a>
          </li>
          <li>
            <a asp-action="Index" asp-controller="Roles" asp-area="UserManagement">
              <i class="fa fa-calendar"></i>
              <span>Role</span>
            </a>
          </li>
        }
          
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
  <div class="sidebar-footer">
    @*
    <a href="#">
      <i class="fa fa-bell"></i>
      <span class="badge badge-pill badge-warning notification">3</span>
    </a>
    <a href="#">
      <i class="fa fa-envelope"></i>
      <span class="badge badge-pill badge-success notification">7</span>
    </a>
    *@
    <a asp-action="Logout" asp-controller="Auth" asp-area="">
      <i class="fa fa-power-off"></i>
    </a>
    
    <a href="#">
      <i class="fa fa-cog"></i>
      @*<span class="badge-sonar"></span>*@
    </a>
  </div>
  </nav>

CoolWebsite/Views/Shared/_HomePageLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="icon" href="~/img/Homepage/d5802db4-4b7b-48a1-a67a-e0b15f34bafb_200x200.png">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Actor">
    <link rel="stylesheet" href="~/lib/bootstrap/homepage/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/fonts/simple-line-icons.min.css">
    <link rel="stylesheet" href="~/lib/css/Profile-Card.css">
    <link rel="stylesheet" href="~/css/Main/homepage.css"/>
    <link rel="stylesheet" href="~/css/site.css">
    



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar" style="padding: 0;">
    <div class="container">
        <img src="~/img/Homepage/d5802db4-4b7b-48a1-a67a-e0b15f34bafb_200x200.png" width="60" height="60" alt="Logo"/>
        <a class="navbar-brand logo" asp-action="HomePage" asp-controller="Home" asp-area="">MSyhler</a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
            <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"
             id="navcol-1">
            <ul class="nav navbar-nav ml-auto">
                @await RenderSectionAsync("NavBar", true)
               
                @{
                    var isAuthenticated = User.Identity.IsAuthenticated;
                    if (isAuthenticated)
                    {


                        <li class="nav-item" role="presentation">
                            <a class="nav-link" asp-area="Financial" asp-controller="Home" asp-action="Index">Financial</a>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item" role="presentation">
                            <a class="nav-link sign-in" >Sign in</a>
                        </li>

                    }
                }

            </ul>
        </div>
    </div>
    
    @{
        if (isAuthenticated)
        {
            <div style="float: left">
                <a class="link" asp-area="" asp-controller="Auth" asp-action="Logout">@User.Identity.Name : Sign out</a>
            </div>
        }
    }
</nav>
@RenderBody()

<footer class="page-footer dark">
    <div class="container">
        <div class="row">
            <div class="col">
                <h5>Get started</h5>
                <ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a asp-action="Logout" asp-controller="Auth" asp-area="" class="default-link">Log out</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a class="sign-in default-link">Sign In</a>
                        </li>
                    }
                    <li>
                        <a class="default-link">Sign up (Currently disabled)</a>
                    </li>
                </ul>
            </div>
            <div class="col">
                <div>
                    <h5>About me</h5>
                    <ul>
                        <li>
                            <a class="default-link" asp-action="Index" asp-controller="Home" asp-area="">Who am i</a>
                        </li>
                        <li>
                            <a class="default-link" asp-action="Index" asp-controller="Home" asp-area="">Courses</a>
                        </li>
                        <li>
                            <a class="default-link" asp-action="Index" asp-controller="Home" asp-area="">Skill Set</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col">
                <h5>Projects</h5>
                <ul>
                    <li>
                        <a class="default-link" asp-action="CoolWebsiteProject" asp-controller="Home" asp-area="">CoolWebsite</a>
                    </li>
                    <li>
                        <a class="default-link" >Messaging App</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <p>© 2020 Morten Syhler&nbsp;All Rights Reserved<br></p>
    </div>
</footer>

</body>


<!-- 
modal
-->
<div class="modal" tabindex="-1" role="dialog" id="login-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="container p-5">
                <div class="block-heading">
                    <h2 class="text-info">Log In</h2>
                </div>
                <form id="login-form">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input class="form-control item" type="email" id="email" name="email">
                    </div>
                    
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input class="form-control" type="password" id="password" name="password">
                    </div>
                    
                    <div id="error-div">
                        
                    </div>
                    
                    <div class="form-group">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="checkbox">
                            <label class="form-check-label" for="checkbox">Remember me</label>
                        </div>
                    </div>
                    
                    <button class="btn btn-primary btn-block" type="submit" id="login-btn">Log In</button>
                </form>
            </div>
        </div>
    </div>
</div>


<script src="~/js/homepage/common.js"></script>



<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
<script src="~/lib/js/theme.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

@await RenderSectionAsync("Scripts", false)


</html>

CoolWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/img/Homepage/d5802db4-4b7b-48a1-a67a-e0b15f34bafb_200x200.png">
    <link rel="stylesheet" href="~/lib/jquery-ui-1.12.1/jquery-ui.min.css"/>
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.14.0-web/css/all.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapDark.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/Main/MainLayout.css"/>
    <link rel="stylesheet" href="~/css/Main/sidebarNew.css"/>
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.14.0-web/css/all.min.css"/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    @await RenderSectionAsync("StyleSheets", false)
</head>
<body>

<div class="page-wrapper chiller-theme toggled">

    @await Html.PartialAsync("Sidebar")


    <main class="page-content" style=" width: 100%;
                                          height: 100vh;">
        <div class="container">
            @RenderBody()
        </div>
    </main>
</div>


<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script type="text/javascript" src="~/lib/js/moment.js"></script>
<script type="text/javascript" src="~/lib/jquery-ui-1.12.1/jquery-ui.min.js"></script>
<script type="text/javascript" src="~/js/JQueryValidationCustomMethods.js"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>